### ISSUE TITLE
version 1.6.0 does not work with IE 11

### ISSUE THREAD

**Issue by ghost** [toolsforresearch/tfr_responsive#18] opened 2015-11-26 10:53 UTC
both version 1.5.0 and 1.6.0 throw this error (on limesurvey 2.06+) when used on Internet Explorer 11 (the version that comes with Windows 8.1):

"Internet Explorer 8 or lower is not supported in this theme."

When I click on OK, the survey appears, but the layout looks bad, and it's impossible to select an answer.

**Comment by Jan-E** [comment] 2015-11-26 11:32
Do you get this error as well on our demo survey?
https://survey.toolsforresearch.com/index.php/123456/lang-en

We tested this on Windows 8.1 Pro with Internet Explorer 11 and could not reproduce it. See screenshot:
![windows 8 x64](https://cloud.githubusercontent.com/assets/1757825/11422112/ad94ecee-9439-11e5-8cfc-f99c4fb55352.png)

**Comment by ghost** [comment] 2015-11-26 12:00
Hi, 
No I don't see the error on the url you provided.

You can see the error here (the token has already been used, but the error is still shown):
http://support.unit4venice.be/limesurvey/index.php?r=survey/index/sid/425522/token/jmhOCRgoMqDrmPw/lang/nl
![ie11](https://cloud.githubusercontent.com/assets/16031423/11422598/992c05e0-943d-11e5-9246-d0138fab8820.PNG)

**Comment by Jan-E** [comment] 2015-11-26 12:29
I do not get the error there either. Did you close the issue because you found out what was wrong on that URL?

**Comment by tvanover99** [comment] 2015-11-26 12:37
Hi,

I didn't mean to close the issue, must have been an error on my behalf. Can you reopen that issue? Or do I need to log a new one?



Tom Van Overbeke
Support Engineer
[Unit4]
In business for people.
Integrity | Respect | Engaging | Results Driven

Unit4 C-Logic nv

Rijselstraat 247, 8200 Brugge, Belgium
T  +32 50 39 13 36
E  Tom.Van.Overbeke@unit4.com
This message and any attachment(s) are intended only for the use of the named recipient and may contain information that is privileged, confidential or otherwise exempt from disclosure under applicable law. If you are not the intended recipient, please notify the sender by return e-mail and delete this message from your system. Do not disclose the contents of this document to any other persons. Violation of this notice may be unlawful. Please note that internet communications are not secure and e-mails are susceptible to change. Thank you for your cooperation.

**Comment by ghost** [comment] 2015-11-26 12:39
Hi, I made a mistake. the issue is not resolved.
How can I help you debug this issue?

**Comment by Jan-E** [comment] 2015-11-26 12:54
I still cannot reproduce the error. Not on Win 81. with IE11, not on Win 7 with IE11.

@tammoterhark Do you get an error message with IE11 on
http://support.unit4venice.be/limesurvey/index.php?r=survey/index/sid/425522/token/jmhOCRgoMqDrmPw/lang/nl

@tvanover99 Try clearing the cache of your IE11 completely.

**Comment by ghost** [comment] 2015-11-26 12:59
Hi,

I have the same error on another windows 8 pc running IE 10. Clearing the cache doesn't solve it.

**Comment by Jan-E** [comment] 2015-11-26 13:11
Are you running IE in compatibility mode? I only get the error when I choose '8' using the developer tools. F12 bottom right:

![capture](https://cloud.githubusercontent.com/assets/1757825/11423732/470b8d58-9447-11e5-9852-e9721a70fb68.PNG)

This produces no error, because the conditinal comment is not triggered. View source / Ctrl-U:

```
<!--[if lte IE 8]>
    <script type="text/javascript">
         alert('Internet Explorer 8 or lower is not supported in this theme');
    </script>
<![endif]-->
```

**Comment by tammoterhark** [comment] 2015-11-26 13:17
Hi, using Windows 10 and IE11 I cannot reproduce the error, neither on our own demo, neither on the URL that @tvanover99 sent.

**Comment by Jan-E** [comment] 2015-11-26 13:32
Grabbed a machine with a Dutch IE11 (Win 7 Pro). No dice either:

![knipsel](https://cloud.githubusercontent.com/assets/1757825/11424056/2cb26b86-944a-11e5-9c8b-ea45a58b73aa.PNG)

But there is a difference in the version. The up2date version is IE 11.0.25, whereas @tvanover99 's IE11 is reporting 11.0.14 and an older, but fairly recent KB.

**Comment by ghost** [comment] 2015-11-26 14:43
Hi,

I've found the problem. You set me on the right path…

'intranetsites met de compatibiliteitsweergave weergeven' needed to be unchecked, that solved the problem!

[cid:image001.png@01D12861.387E6000]

Thanks for the excellen support.

**Comment by Jan-E** [comment] 2015-11-26 14:57
OK. Good luck with your klanttevredenheidsonderzoek.

**Closed as completed by Jan-E** 2015-11-26 14:57 UTC
Labels: bug
